elastic:
  volumeClaimTemplate:
    accessModes: [ "ReadWriteOnce" ]
    storageClassName: do-block-storage
    resources:
      requests:
        storage: 2Gi
vault: # https://www.vaultproject.io/docs/platform/k8s/helm/examples/standalone-tls
  global:
    enabled: true
    tlsDisable: false
  server:
    extraEnvironmentVars:
      VAULT_CACERT: /vault/userconfig/vault-server-tls/vault.crt
      VAULT_CLIENT_KEY: /vault/userconfig/vault-server-tls/vault.key
      VAULT_CLIENT_CERT: /vault/userconfig/vault-server-tls/vault.crt
    extraVolumes:
      - type: secret
        name: vault-server-tls # Matches the ${SECRET_NAME} from above
    standalone:
      enabled: true
      config: |
        listener "tcp" {
          address = "[::]:8200"
          cluster_address = "[::]:8201"
          tls_cert_file = "/vault/userconfig/vault-server-tls/vault.crt"
          tls_key_file  = "/vault/userconfig/vault-server-tls/vault.key"
          tls_client_ca_file = "/vault/userconfig/vault-server-tls/vault.crt"
        }

        storage "file" {
          path = "/vault/data"
        }
