harbor:
  harborAdminPassword: Harbor12345
  expose:
    type: nodePort
    tls:
      enabled: true
      certSource: secret
      secret:
        secretName: harbor-certs
  externalURL: https://core.harbor.domain:30003
  nodePort:
    name: harbor
    ports:
      http:
        port: 80
        nodePort: 30002
      https:
        port: 443
        nodePort: 30003

elastic:
  volumeClaimTemplate:
    accessModes: [ "ReadWriteOnce" ]
    storageClassName: "hostpath"
    resources:
      requests:
        storage: 100M