# Default values for Odysseia.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

config:
  externalRepo: true
  privateImagesInRepo: false
  environment: minikube
  tls: true
  sidecarOverwrite: true
  pullPolicy: Never
  harborPullPolicy: Always
  replicas:
    low: 1
    medium: 2
    high: 4
  initialDelayLiveness: 20
  initialDelayReadiness: 1
  periodSeconds: 20

services:
  backend:
    labels: {
      domain: backend
    }
  solon:
    name: "solon"
    requests:
      memory: "64Mi"
      cpu: "100m"
    limits:
      memory: "128Mi"
      cpu: "250m"
  drakon:
    name: "drakon"

images:
  imageRepo: core.harbor.domain:30003/odysseia/
  pullSecret: harbor-images
  tag: 4952f80
  odysseiaapi:
    repo: solon
  init:
    repo: drakon

envVariables:
  solon:
    port: 5443
    vaultAuthMethod: kubernetes
    vaultRole: solon
  solonService: https://solon:5443
  vaultService: https://vault:8200
  elasticService: https://elastic-master:9200
  elasticUser: elastic

tlsConfig:
  rootPath: /etc/certs
  vault:
    name: vault-server-tls
    secretName: vault-server-tls
    path: /etc/certs/vault
    enabled: true
  elastic:
    name: elastic-certificate-pem
    secretName: elastic-certificate-pem
    path: /app/config/certs
  mounts:
    - name: solon-certs
      secretName: solon-tls-certs
      path: /etc/certs/solon

serviceAccount:
  name: solon-access-sa

namespaceOverride: odysseia

role:
  name: api-access
