# Default values for Odysseia.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

config:
  environment: minikube
  tls: true
  pullPolicy: Never
  replicas:
    low: 1
    medium: 2
    high: 4
  initialDelayLiveness: 20
  initialDelayReadiness: 1
  periodSeconds: 20

services:
  backend:
    labels: {
      domain: backend
    }
  solon:
    name: "solon"
    requests:
      memory: "64Mi"
      cpu: "100m"
    limits:
      memory: "128Mi"
      cpu: "250m"
  drakon:
    name: "drakon"

images:
  tag: 83964a0
  solon:
    repo: solon
  drakon:
    repo: drakon

envVariables:
  solon:
    port: 5000
    extraEnvs:
      - name: VAULT_SERVICE
        value: http://vault:8200
      - name: AUTH_METHOD
        value: kubernetes
      - name: VAULT_ROLE
        value: solon
      - name: ELASTIC_SEARCH_SERVICE
        value: https://elastic-master:9200
      - name: ELASTIC_SEARCH_USER
        value: elastic
      - name: ELASTIC_SEARCH_PASSWORD
        valueFrom:
          secretKeyRef:
            name: elastic-root-secret
            key: password
  drakon:
    extraEnvs:
      - name: ELASTIC_SEARCH_SERVICE
        value: https://elastic-master:9200
      - name: ELASTIC_SEARCH_USER
        value: elastic
      - name: ELASTIC_SEARCH_PASSWORD
        valueFrom:
          secretKeyRef:
            name: elastic-root-secret
            key: password

esConfig:
  elasticService: https://elastic-master:9200
  elasticUser: elastic
  elasticPassword: zyldw9RLDBn1uNcul20Wvb1R

secretMounts:
  - name: elastic-certificate-pem
    secretName: elastic-certificate-pem
    path: /app/config/certs

serviceAccount:
  name: access-sa

namespaceOverride: odysseia

role:
  name: api-access