apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: odysseia-ingress
#  annotations:
#    nginx.ingress.kubernetes.io/rewrite-target: /
  labels:
    app: odysseia-ingress
spec:
  defaultBackend:
    service:
      name: sokrates-service
      port:
        number: {{ .Values.envVariables.sokrates.port }}
  rules:
    - http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: pheidias-service
                port:
                  number: {{ .Values.envVariables.pheidias.port }}
          - pathType: Prefix
            path: /sokrates/v1
            backend:
              service:
                name: sokrates-service
                port:
                  number: {{ .Values.envVariables.sokrates.port }}
          - pathType: Prefix
            path: /herodotos/v1
            backend:
              service:
                name: herodotos-service
                port:
                  number: {{ .Values.envVariables.herodotos.port }}
          - pathType: Prefix
            path: /alexandros/v1
            backend:
              service:
                name: alexandros-service
                port:
                  number: {{ .Values.envVariables.alexandros.port }}
          - pathType: Prefix
            path: /dionysios/v1
            backend:
              service:
                name: dionysios-service
                port:
                  number: {{ .Values.envVariables.dionysios.port }}
          - pathType: Prefix
            path: /solon/v1
            backend:
              service:
                name: solon-service
                port:
                  number: {{ .Values.envVariables.solon.port }}
          - pathType: Prefix
            path: /ploutarchos
            backend:
              service:
                name: ploutarchos-service
                port:
                  number: {{ .Values.envVariables.ploutarchos.port }}
          - pathType: Prefix
            path: /swagger
            backend:
              service:
                name: ploutarchos-service
                port:
                  number: {{ .Values.envVariables.ploutarchos.port }}
