apiVersion: apps/v1
kind: Deployment
metadata:
  name: athena
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
      annotations:
        perikles/hostname: perikles
        perikles/validity: "10"
        perikles/accesses: solon;herodotos
    spec:
      containers:
        - name: nginx
          image: nginx:1.14.2
          ports:
            - containerPort: 80
          volumeMounts:
            - name: perikles
              mountPath: "/etc/ssl/perikles"
              readOnly: true
            - name: solon
              mountPath: "/etc/ssl/solon"
              readOnly: true
            - name: herodotos
              mountPath: "/etc/ssl/herodotos"
              readOnly: true
      volumes:
        - name: perikles
          secret:
            secretName: perikles-test-secret
            items:
              - key: tls.key
                path: tls.key
              - key: tls.crt
                path: tls.crt
        - name: solon
          secret:
            secretName: solon-test-secret
            items:
              - key: tls.key
                path: tls.key
              - key: tls.crt
                path: tls.crt
        - name: herodotos
          secret:
            secretName: herodotos-test-secret
            items:
              - key: tls.key
                path: tls.key
              - key: tls.crt
                path: tls.crt
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
