apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
      annotations:
        perikles/hostname: perikles
        perikles/validity: "10"
        perikles/accesses: solon;herodotos
    spec:
      containers:
        - name: nginx
          image: nginx:1.14.2
          ports:
            - containerPort: 80
          volumeMounts:
            - name: foo
              mountPath: "/etc/ssl"
              readOnly: true
      volumes:
        - name: foo
          secret:
            secretName: perikles-test-secret
            items:
              - key: tls.key
                path: perikles/tls.key
              - key: tls.crt
                path: perikles/tls.crt
        - name: foo
          secret:
            secretName: solon-test-secret
            items:
              - key: tls.key
                path: solon/tls.key
              - key: tls.crt
                path: solon/tls.crt
        - name: foo
          secret:
            secretName: solon-test-secret
            items:
              - key: tls.key
                path: herodotos/tls.key
              - key: tls.crt
                path: herodotos/tls.crt
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
