apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ template "solon.uname" . }}"
  namespace: {{ template "solon.namespace" . }}
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}"
    env: {{ .Values.config.environment }}
    app: "{{ template "solon.uname" . }}"
    {{- range $key, $value := .Values.services.backend.labels }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
spec:
  replicas: {{ int .Values.config.replicas.low }}
  selector:
    matchLabels:
      app: "{{ template "solon.uname" . }}"
  template:
    metadata:
      labels:
        app: {{ template "solon.uname" . }}
        release: {{ .Release.Name }}
        version: {{ .Values.images.tag }}
      annotations:
        elastic/indices: "dictionary;grammar;text;quiz"
        elastic/roles: "api;seeder;hybrid"
        perikles/hostname: "solon"
        perikles/validity: "10"
    spec:
      serviceAccountName: {{ template "solon.serviceAccountName" . }}
      {{- if .Values.config.externalRepo | quote }}
      imagePullSecrets:
        - name: {{ .Values.images.pullSecret }}
      {{- end}}
      initContainers:
        - name: "{{ template "drakon.uname" . }}"
          {{- if .Values.config.externalRepo | quote }}
          image: {{ .Values.images.imageRepo}}{{ .Values.images.init.repo }}:{{ .Values.images.tag }}
          imagePullPolicy: {{ .Values.config.harborPullPolicy }}
          {{ else }}
          image: {{ .Values.images.imageRepo}}{{ .Values.images.init.repo }}:{{ .Values.images.tag }}
          imagePullPolicy: {{ .Values.config.pullPolicy }}
          {{- end}}
          env:
          - name: ENV
            value: {{ .Values.config.environment }}
          - name: TLS_ENABLED
            value: {{ .Values.config.tls | quote }}
          - name: SIDECAR_OVERWRITE
            value:  {{ .Values.config.sidecarOverwrite | quote }}
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: ELASTIC_INDEXES
            valueFrom:
              fieldRef:
                fieldPath: metadata.annotations['elastic/indices']
          - name: ELASTIC_ROLES
            valueFrom:
              fieldRef:
                fieldPath: metadata.annotations['elastic/roles']
          - name: ELASTIC_SEARCH_SERVICE
            value: {{ .Values.envVariables.elasticService }}
          - name: ELASTIC_SEARCH_USER
            value: {{ .Values.envVariables.elasticUser }}
          - name: ELASTIC_SEARCH_PASSWORD
            valueFrom:
              secretKeyRef:
                name: elastic-root-secret
                key: password
          volumeMounts:
            - name: {{ .Values.tlsConfig.elastic.name }}
              mountPath: {{ .Values.tlsConfig.elastic.path }}
              readOnly: true
      containers:
        - name: "{{ template "solon.uname" . }}"
          {{- if .Values.config.externalRepo | quote }}
          image: {{ .Values.images.imageRepo}}{{ .Values.images.odysseiaapi.repo }}:{{ .Values.images.tag }}
          imagePullPolicy: {{ .Values.config.harborPullPolicy }}
          {{ else }}
          image: {{ .Values.images.odysseiaapi.repo }}:{{ .Values.images.tag }}
          imagePullPolicy: {{ .Values.config.pullPolicy }}
          {{- end}}
          env:
          - name: ENV
            value: {{ .Values.config.environment }}
          - name: TLS_FILES
            value: {{ .Values.tlsConfig.path }}
          - name: TLS_ENABLED
            value: {{ .Values.config.tls | quote }}
          - name: SIDECAR_OVERWRITE
            value:  {{ .Values.config.sidecarOverwrite | quote }}
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: CERT_ROOT
            value: {{ .Values.tlsConfig.rootPath }}
          - name: VAULT_TLS
            value:  {{ .Values.tlsConfig.vault.enabled | quote }}
          - name: VAULT_SERVICE
            value: {{ .Values.envVariables.vaultService }}
          - name: AUTH_METHOD
            value: {{ .Values.envVariables.solon.vaultAuthMethod }}
          - name: VAULT_ROLE
            value: {{ .Values.envVariables.solon.vaultRole }}
          - name: ELASTIC_SEARCH_SERVICE
            value: {{ .Values.envVariables.elasticService }}
          - name: ELASTIC_SEARCH_USER
            value: {{ .Values.envVariables.elasticUser }}
          - name: ELASTIC_SEARCH_PASSWORD
            valueFrom:
              secretKeyRef:
                name: elastic-root-secret
                key: password
          volumeMounts:
            - name: {{ .Values.tlsConfig.vault.name }}
              mountPath: {{ .Values.tlsConfig.vault.path }}
              readOnly: true
            - name: {{ .Values.tlsConfig.elastic.name }}
              mountPath: {{ .Values.tlsConfig.elastic.path }}
              readOnly: true
            {{- range .Values.tlsConfig.mounts }}
            - name: {{ .name }}
              mountPath: {{ .path }}
              readOnly: true
            {{- end }}
          ports:
            - containerPort: {{ .Values.envVariables.solon.port }}
          livenessProbe:
            httpGet:
              scheme: HTTPS
              path: /solon/v1/health
              port: {{ .Values.envVariables.solon.port }}
            initialDelaySeconds: {{ .Values.config.initialDelayLiveness }}
            periodSeconds: {{ .Values.config.periodSeconds }}
          readinessProbe:
            httpGet:
              scheme: HTTPS
              path: /solon/v1/ping
              port: {{ .Values.envVariables.solon.port }}
            initialDelaySeconds: {{ .Values.config.initialDelayReadiness }}
            periodSeconds: {{ .Values.config.periodSeconds }}
          resources:
            requests:
              memory: {{ .Values.services.solon.requests.memory }}
              cpu: {{ .Values.services.solon.requests.cpu }}
            limits:
              memory: {{.Values.services.solon.limits.memory}}
              cpu: {{.Values.services.solon.limits.memory}}
      volumes:
        - name: {{ .Values.tlsConfig.vault.name }}
          secret:
            secretName: {{ .Values.tlsConfig.vault.secretName }}
        - name: {{ .Values.tlsConfig.elastic.name }}
          secret:
            secretName: {{ .Values.tlsConfig.elastic.secretName }}
        {{- range .Values.tlsConfig.mounts }}
        - name: {{ .name }}
          secret:
            secretName: {{ .secretName }}
            {{- if .defaultMode }}
            defaultMode: {{ .defaultMode }}
        {{- end }}
  {{- end }}