apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: {{ template "solon.namespace" . }}
  name: {{ template "solon.bindingName" $ }}
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "solon.roleName" . }}
subjects:
- kind: ServiceAccount
  name: {{ template "solon.serviceAccountName" . }}
  namespace: {{ template "solon.namespace" . }}
