apiVersion: batch/v1
kind: Job
metadata:
  name: herakleitos
  labels:
    app: herakleitos
spec:
  template:
    metadata:
      labels:
        app: herakleitos
        release: {{ .Release.Name }}
        version: {{ .Values.images.tag }}
    spec:
      containers:
        - image: {{ .Values.images.herakleitos.repo }}:{{ .Values.images.tag }}
          name: herakleitos
          env:
            - name: ELASTIC_SEARCH_SERVICE
              valueFrom:
                configMapKeyRef:
                  name: {{ template "odysseia.fullname" . }}-config
                  key: elasticService
            - name: ELASTIC_SEARCH_USER
              valueFrom:
                configMapKeyRef:
                  name: {{ template "odysseia.fullname" . }}-config
                  key: elasticUser
            - name: ELASTIC_SEARCH_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: {{ template "odysseia.fullname" . }}-config
                  key: elasticPassword
          imagePullPolicy: {{ .Values.config.pullPolicy }}
      restartPolicy: Never
  backoffLimit: 3
