apiVersion: v1
kind: Service
metadata:
  name: {{ template "queue.uname" . }}
  namespace: {{ template "namespace" . }}
spec:
  ports:
    - name: grpc-port
      protocol: TCP
      port: 50000
      targetPort: 50000
    - name: api-port
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: rest-port
      protocol: TCP
      port: 9090
      targetPort: 9090
  selector:
    app: {{ template "queue.uname" . }}
