apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: "{{ template "queue.uname" . }}"
  namespace: {{ template "namespace" . }}
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}"
    env: {{ .Values.config.environment }}
    app: "{{ template "queue.uname" . }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "{{ template "queue.uname" . }}"
  serviceName: "kubemq"
  template:
    metadata:
      labels:
        app: "{{ template "queue.uname" . }}"
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: kubemq
          image: {{ .Values.images.queue.repo }}:{{ .Values.images.tag }}
          imagePullPolicy: {{ .Values.config.pullPolicy }}
          volumeMounts:
            - name: config-volume
              mountPath: ./kubemq/config
          ports:
            - name: grpc-port
              containerPort: 50000
              protocol: TCP
            - name: api-port
              containerPort: 8080
              protocol: TCP
            - name: rest-port
              containerPort: 9090
              protocol: TCP
      volumes:
        - name: config-volume
          configMap:
            name: kubemq-config
            items:
              - key: CONFIG
                path: config.yaml