# Default values for Odysseia.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

config:
  environment: minikube
  pullPolicy: Never
  replicas:
    low: 1
    medium: 2
    high: 4
  initialDelayLiveness: 20
  initialDelayReadiness: 1
  periodSeconds: 20

services:
  backend:
    labels: {
      domain: backend
    }
  ptolemaios:
    name: "ptolemaios"
    requests:
      memory: "64Mi"
      cpu: "100m"
    limits:
      memory: "128Mi"
      cpu: "250m"
  periandros:
    name: "periandros"

images:
  tag: b463af3
  ptolemaios:
    repo: ptolemaios
  periandros:
    repo: periandros

envVariables:
  ptolemaios:
    port: 5001
  solonService: http://solon-service:5000
  vaultService: http://vault:8200
