# Default values for Odysseia.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

config:
  environment: minikube
  externalRepo: true
  privateImagesInRepo: false
  tls: true
  pullPolicy: Never
  replicas:
    low: 1
    medium: 2
    high: 4
  initialDelayLiveness: 20
  initialDelayReadiness: 1
  periodSeconds: 20

services:
  frontend:
    labels: {
      domain: frontend
    }
  odysseiaapi:
    name: "pheidias"
    requests:
      memory: "64Mi"
      cpu: "100m"
    limits:
      memory: "128Mi"
      cpu: "250m"

images:
  tag: 4952f80
  imageRepo: core.harbor.domain:30003/odysseia/
  pullSecret: harbor-images
  odysseiaapi:
    repo: pheidias

envVariables:
  nodeEnv: production
  odysseiaapi:
    port: 3000

namespaceOverride: odysseia
