# Default values for Odysseia.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

config:
  environment: minikube
  pullPolicy: Never
  inClusterHarbor: true
  inClusterElastic: true
  inClusterElasticStack: false
  inClusterKibana: true
  inClusterVault: true
  loadTests: true
  systemTests: true

envVariables:
  pheidias:
    port: 3000
  alexandros:
    port: 5000
  dionysios:
    port: 5000
  sokrates:
    port: 5000
  herodotos:
    port: 5000
  solon:
    port: 5000
  ploutarchos:
    port: 8080
  xerxes:
    port: 8089
