# Default values for Odysseia.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

config:
  environment: minikube
  pullPolicy: Never
  inClusterElastic: true
  loadTests: true
  systemTests: true
  replicas:
    low: 1
    medium: 2
    high: 4
  initialDelayLiveness: 20
  initialDelayReadiness: 1
  periodSeconds: 20

services:
  hippokrates:
    testing: true
    name: "hippokrates"
    # additionals labels
    labels: {
              domain: testing
    }
  alexandros:
    requests:
      memory: "64Mi"
      cpu: "100m"
    limits:
      memory: "128Mi"
      cpu: "250m"
  dionysos:
    requests:
      memory: "64Mi"
      cpu: "100m"
    limits:
      memory: "128Mi"
      cpu: "250m"
  herodotos:
    requests:
      memory: "64Mi"
      cpu: "250m"
    limits:
      memory: "128Mi"
      cpu: "500m"
  sokrates:
    requests:
      memory: "64Mi"
      cpu: "100m"
    limits:
      memory: "128Mi"
      cpu: "250m"

images:
  tag: eb4f981
  anaximander:
    repo: anaximander
  alexandros:
    repo: alexandros
  dionysos:
    repo: dionysos
  pheidias:
    repo: pheidias
  sokrates:
    repo: sokrates
  parmenides:
    repo: parmenides
  demokritos:
    repo: demokritos
  herodotos:
    repo: herodotos
  herakleitos:
    repo: herakleitos
  ploutarchos:
    repo: ploutarchos
  hippokrates:
    repo: hippokrates
  xerxes:
    repo: xerxes

envVariables:
  pheidias:
    nodeEnv: production
    port: 3000
  alexandros:
    port: 5000
  dionysos:
    port: 5000
    alexandrosUrl: http://alexandros-service:5000
  sokrates:
    port: 5000
  herodotos:
    port: 5000
  ploutarchos:
    port: 8080
  xerxes:
    alexandrosHost: http://alexandros-service:5000
    alexandrosPort: 8086
    dionysosHost: http://dionysos-service:5000
    dionysosPort: 8087
    herodotosHost: http://herodotos-service:5000
    herodotosPort: 8088
    sokratesHost: http://sokrates-service:5000
    sokratesPort: 8089
    port: 8089
    locustUsers: 100
    spawnRate: 5
  elastic:
    elasticService: http://elasticsearch-master:9200
    elasticUser: elastic
    elasticPassword: odysseia