# Default values for Odysseia.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

config:
  environment: minikube
  pullPolicy: Never
  inClusterElastic: true
  inClusterElasticStack: false
  inClusterKibana: true
  inClusterVault: true
  loadTests: true
  systemTests: true
  replicas:
    low: 1
    medium: 2
    high: 4
  initialDelayLiveness: 20
  initialDelayReadiness: 1
  periodSeconds: 20

services:
  backend:
    labels: {
      domain: backend
    }
  hippokrates:
    testing: true
    name: "hippokrates"
    # additionals labels
    labels: {
        domain: testing
    }
  alexandros:
    name: "alexandros"
    requests:
      memory: "64Mi"
      cpu: "100m"
    limits:
      memory: "128Mi"
      cpu: "250m"
  dionysos:
    name: "dionysos"
    requests:
      memory: "64Mi"
      cpu: "100m"
    limits:
      memory: "128Mi"
      cpu: "250m"
  herodotos:
    name: "herodotos"
    requests:
      memory: "64Mi"
      cpu: "250m"
    limits:
      memory: "128Mi"
      cpu: "500m"
  sokrates:
    name: "sokrates"
    requests:
      memory: "64Mi"
      cpu: "100m"
    limits:
      memory: "128Mi"
      cpu: "250m"
  solon:
    name: "solon"
  ptolemaios:
    name: "ptolemaios"

images:
  tag: c1d072e
  anaximander:
    repo: anaximander
  alexandros:
    repo: alexandros
  dionysos:
    repo: dionysos
  pheidias:
    repo: pheidias
  sokrates:
    repo: sokrates
  parmenides:
    repo: parmenides
  demokritos:
    repo: demokritos
  herodotos:
    repo: herodotos
  herakleitos:
    repo: herakleitos
  ploutarchos:
    repo: ploutarchos
  hippokrates:
    repo: hippokrates
  solon:
    repo: solon
  ptolemaios:
    repo: ptolemaios
  xerxes:
    repo: xerxes

envVariables:
  pheidias:
    nodeEnv: production
    port: 3000
  alexandros:
    port: 5000
  dionysos:
    port: 5000
  sokrates:
    port: 5000
  herodotos:
    port: 5000
  solon:
    port: 5000
    extraEnvs:
      - name: VAULT_SERVICE
        value: http://vault:8200
      - name: AUTH_METHOD
        value: kubernetes
      - name: VAULT_ROLE
        value: solon
      - name: ELASTIC_PASSWORD
        valueFrom:
          secretKeyRef:
            name: elastic-root-secret
            key: password
  ploutarchos:
    port: 8080
  xerxes:
    alexandrosHost: http://alexandros-service:5000
    alexandrosPort: 8086
    dionysosHost: http://dionysos-service:5000
    dionysosPort: 8087
    herodotosHost: http://herodotos-service:5000
    herodotosPort: 8088
    sokratesHost: http://sokrates-service:5000
    sokratesPort: 8089
    port: 8089
    locustUsers: 100
    spawnRate: 5

esConfig:
  elasticService: https://elastic-master:9200
  elasticUser: elastic
  elasticPassword: zyldw9RLDBn1uNcul20Wvb1R

secretMounts:
  - name: elastic-certificate-pem
    secretName: elastic-certificate-pem
    path: /app/config/certs
