apiVersion: v1
kind: Service
metadata:
  name: solon-service
spec:
  selector:
    app: "{{ template "solon.uname" . }}"
  ports:
    - name: "http"
      port: {{ .Values.envVariables.alexandros.port }}
      targetPort: {{ .Values.envVariables.alexandros.port }}
