apiVersion: v1
kind: Service
metadata:
  name: {{ template "odysseiaapi.uname" . }}
  namespace: {{ template "namespace" . }}
spec:
  selector:
    app: {{ template "odysseiaapi.uname" . }}
  ports:
    - name: "http"
      port: {{ .Values.envVariables.odysseiaapi.port }}
      targetPort: {{ .Values.envVariables.odysseiaapi.port }}
