apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "perikles.clusterBindingName" $ }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "perikles.clusterRoleName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "perikles.serviceAccountName" . }}
    namespace: {{ template "perikles.namespace" . }}