apiVersion: v1
kind: Service
metadata:
  name: ploutarchos-service
spec:
  selector:
    app: ploutarchos
  ports:
    - name: "http"
      port: {{ .Values.config.port }}
      targetPort: {{ .Values.config.port }}
