apiVersion: v1
kind: Service
metadata:
  name: {{ template "docs.uname" . }}
  namespace: {{ template "docs.namespace" . }}
spec:
  selector:
    app: {{ template "docs.uname" . }}
  ports:
    - name: "http"
      port: {{ .Values.config.port }}
      targetPort: {{ .Values.config.port }}
